@extends('admin.layout')
@section('content')
	<div class="header col-md-12" >
	    <div class="title col-md-8">
	        <h2><i class="fa fa-tag"></i> Generate New Code</h2>
	    </div>
	    <div class="buttons col-md-4 text-right">
	        <button onclick="location.href='admin/maintenance/codes'" type="button" class="btn btn-default"><i class="fa fa-angle-double-left"></i> Back</button>
	        <button onclick="$('#code-add-form').submit();" type="button" class="btn btn-primary"><i class="fa fa-save"></i> Generate</button>
	    </div>
    </div>

    <div class="col-md-12 form-group-container">
        
        <table class="table table-hover table-bordered">
                            <caption>
                    Date :{{$membership_code_sale->created_at}} <br>
                    Membership Sale OR # {{$membership_code_sale->membershipcode_or_num}} <br>
                    OR - CODE : {{$membership_code_sale->membershipcode_or_code}} <br>
                    Vocuher # {{$membership_code_sale->voucher_id}} <br>
                    Sold To : {{$membership_code_sale->sold_to}} <br>
                    Generated By : {{$membership_code_sale->generated_by}} <br>
                    Payment : {{$membership_code_sale->payment == 0 ? 'Wallet' : 'Cash' }} <br>
                    Total Amount : {{number_format ( $membership_code_sale->total_amount, 2 , "." ,  "," )}} <br>    
                </caption>
            <thead>
                <tr>
                    <th>Code pin</th>
                    <th>Code</th>
                    <th>Membership</th>
                    <th>Price</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($_codes as $code)
                    <tr>
                        <td>{{$code->code_pin}}</td>
                        <td>{{$code->code_activation}}</td>
                        <td>{{$code->membership_name}}</td>
                        <td>{{number_format ( $code->membership_price, 2 , "." ,  "," )}}</td>
                    </tr>
                @endforeach
            </tbody>

            <table class="table table-hover table-bordered">
                <caption>Included Products</caption>
                <thead>
                    <tr>
                        <td>Product ID</td>
                        <td>Product Name</td>
                        <td>Product Qty</td>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($_product as $product)
                        <tr>
                            <td>{{$product->product_id}}</td>
                             <td>{{$product->product_name}}</td>
                              <td>{{$product->qty}}</td>
                        </tr>
                    @endforeach

                </tbody>
            </table>

            

        </table>
    </div>
@endsection
@section('script')

@endsection