<html>
    <head>
        <title></title>
    </head>
    <body>
        <h1></h1>
        <table style="width: 100%; text-align: center; border-collapse: collapse;">
            <caption style="text-align: left; color: #212F40; text-transform: uppercase; margin: 50px 0;">
                <span style="width: 150px; display: inline-block; font-weight: bold; color: #999999;">Date :</span>{{$membership_code_sale->created_at}} <br>
                <span style="width: 150px; display: inline-block; font-weight: bold; color: #999999;">Membership</span> Sale OR # {{$membership_code_sale->membershipcode_or_num}} <br>
                <span style="width: 150px; display: inline-block; font-weight: bold; color: #999999;">OR - CODE :</span> {{$membership_code_sale->membershipcode_or_code}} <br>
                <span style="width: 150px; display: inline-block; font-weight: bold; color: #999999;">Vocuher: </span># {{$membership_code_sale->voucher_id}} <br>
                <span style="width: 150px; display: inline-block; font-weight: bold; color: #999999;">Sold To :</span> {{$membership_code_sale->sold_to}} <br>
                <span style="width: 150px; display: inline-block; font-weight: bold; color: #999999;">Generated By :</span> {{$membership_code_sale->generated_by}} <br>
                <span style="width: 150px; display: inline-block; font-weight: bold; color: #999999;">Payment :</span> {{$membership_code_sale->payment == 0 ? 'Wallet' : 'Cash' }} <br>
                <span style="width: 150px; display: inline-block; font-weight: bold; color: #999999;">Total Amount :</span> {{number_format ( $membership_code_sale->total_amount, 2 , "." ,  "," )}} <br>
            </caption>
            <thead style="background-color: #3498db; color: #fff; text-transform: uppercase; border: 1px solid #ddddda; border-bottom: 0;">
                <tr style="border-top: 1px solid #ddddda;">
                    <th style="padding: 10px">Code pin</th>
                    <th style="padding: 10px">Code</th>
                    <th style="padding: 10px">Membership</th>
                    <th style="padding: 10px">Price</th>
                </tr>
            </thead>
            <tbody style="border-left: 1px solid #ddddda; border-bottom: 1px solid #ddddda; border-right: 1px solid #ddddda;">
                @foreach ($_codes as $code)
                <tr>
                    <td style="padding: 10px;">{{$code->code_pin}}</td>
                    <td style="padding: 10px;">{{$code->code_activation}}</td>
                    <td style="padding: 10px;">{{$code->membership_name}}</td>
                    <td style="padding: 10px;">{{number_format ( $code->membership_price, 2 , "." ,  "," )}}</td>
                </tr>
                @endforeach
            </tbody>
        </table>
        <div style="margin-top: 50px">
            <table style="width: 100%; border-collapse: collapse; text-align: center;">
                <caption style="padding: 10px 0; font-weight: 400; color: #999999; font-weight: bold; text-transform: uppercase; margin-bottom: 20px;">Included Products</caption>
                <thead style="color: #fff; background-color: #34495e; text-transform: uppercase;">
                    <tr>
                        <th style="padding: 10px;">Product ID</th>
                        <th style="padding: 10px;">Product Name</th>
                        <th style="padding: 10px;">Product Qty</th>
                    </tr>
                </thead>
                <tbody style="border-left: 2px solid #ddddda; border-bottom: 1px solid #ddddda; border-right: 1px solid #ddddda;">
                    @if($_product)
                    @foreach ($_product as $product)
                    <tr style="border-top: 1px solid #ddddda;">
                        <td style="padding: 10px">{{$product->product_id}}</td>
                        <td style="padding: 10px">{{$product->product_name}}</td>
                        <td style="padding: 10px">{{$product->qty}}</td>
                    </tr>
                    @endforeach
                    @endif
                </tbody>
            </table>
        </div>
    </body>
</html>